name: 'Download and Extract Binaries'
description: 'Download binaries from GitHub Release and extract them to a target directory'
inputs:
  tag:
    description: 'Release tag to download from'
    required: true
  target-dir:
    description: 'Target directory to extract binaries to'
    required: true
  naming-convention:
    description: 'Naming convention: npm or pypi'
    required: true
    default: 'npm'
  token:
    description: 'GitHub token for API authentication'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install jq
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Download and extract binaries
      shell: bash
      env:
        TAG: ${{ inputs.tag }}
        REPO: ${{ github.repository }}
        TARGET_DIR: ${{ inputs.target-dir }}
        NAMING: ${{ inputs.naming-convention }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        mkdir -p "$TARGET_DIR"
        
        # Download all platform binaries
        curl -L -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Accept: application/json" \
          "https://api.github.com/repos/${REPO}/releases/tags/${TAG}" | \
          jq -r '.assets[] | select(.name | test("^cc-check-.*\\.(tar\\.gz|zip)$")) | .browser_download_url' | \
          while read url; do
            filename=$(basename "$url")
            curl -L -H "Authorization: token ${GITHUB_TOKEN}" \
              -H "Accept: application/octet-stream" \
              "$url" -o "/tmp/${filename}"
            
            # Extract and rename binaries based on naming convention
            case "$filename" in
              *linux-x86_64.tar.gz)
                tar -xzf "/tmp/${filename}" -C "$TARGET_DIR" || { echo "Failed to extract ${filename}"; exit 1; }
                if [ "$NAMING" = "npm" ]; then
                  mv "$TARGET_DIR/cc-check-linux-x86_64" "$TARGET_DIR/cc-check-linux-x64" || { echo "Failed to rename cc-check-linux-x86_64"; exit 1; }
                  [ -f "$TARGET_DIR/cc-check-linux-x64" ] || { echo "Binary cc-check-linux-x64 not found after extraction"; exit 1; }
                elif [ "$NAMING" = "pypi" ]; then
                  [ -f "$TARGET_DIR/cc-check-linux-x86_64" ] || { echo "Binary cc-check-linux-x86_64 not found after extraction"; exit 1; }
                fi
                ;;
              *linux-arm64.tar.gz)
                tar -xzf "/tmp/${filename}" -C "$TARGET_DIR" || { echo "Failed to extract ${filename}"; exit 1; }
                if [ "$NAMING" = "npm" ]; then
                  mv "$TARGET_DIR/cc-check-linux-arm64" "$TARGET_DIR/cc-check-linux-aarch64" || { echo "Failed to rename cc-check-linux-arm64"; exit 1; }
                  [ -f "$TARGET_DIR/cc-check-linux-aarch64" ] || { echo "Binary cc-check-linux-aarch64 not found after extraction"; exit 1; }
                elif [ "$NAMING" = "pypi" ]; then
                  mv "$TARGET_DIR/cc-check-linux-arm64" "$TARGET_DIR/cc-check-linux-aarch64" || { echo "Failed to rename cc-check-linux-arm64"; exit 1; }
                  [ -f "$TARGET_DIR/cc-check-linux-aarch64" ] || { echo "Binary cc-check-linux-aarch64 not found after extraction"; exit 1; }
                fi
                ;;
              *macos-x86_64.tar.gz)
                tar -xzf "/tmp/${filename}" -C "$TARGET_DIR" || { echo "Failed to extract ${filename}"; exit 1; }
                if [ "$NAMING" = "npm" ]; then
                  mv "$TARGET_DIR/cc-check-macos-x86_64" "$TARGET_DIR/cc-check-darwin-x64" || { echo "Failed to rename cc-check-macos-x86_64"; exit 1; }
                  [ -f "$TARGET_DIR/cc-check-darwin-x64" ] || { echo "Binary cc-check-darwin-x64 not found after extraction"; exit 1; }
                elif [ "$NAMING" = "pypi" ]; then
                  mv "$TARGET_DIR/cc-check-macos-x86_64" "$TARGET_DIR/cc-check-darwin-x86_64" || { echo "Failed to rename cc-check-macos-x86_64"; exit 1; }
                  [ -f "$TARGET_DIR/cc-check-darwin-x86_64" ] || { echo "Binary cc-check-darwin-x86_64 not found after extraction"; exit 1; }
                fi
                ;;
              *macos-arm64.tar.gz)
                tar -xzf "/tmp/${filename}" -C "$TARGET_DIR" || { echo "Failed to extract ${filename}"; exit 1; }
                if [ "$NAMING" = "npm" ]; then
                  mv "$TARGET_DIR/cc-check-macos-arm64" "$TARGET_DIR/cc-check-darwin-arm64" || { echo "Failed to rename cc-check-macos-arm64"; exit 1; }
                  [ -f "$TARGET_DIR/cc-check-darwin-arm64" ] || { echo "Binary cc-check-darwin-arm64 not found after extraction"; exit 1; }
                elif [ "$NAMING" = "pypi" ]; then
                  mv "$TARGET_DIR/cc-check-macos-arm64" "$TARGET_DIR/cc-check-darwin-arm64" || { echo "Failed to rename cc-check-macos-arm64"; exit 1; }
                  [ -f "$TARGET_DIR/cc-check-darwin-arm64" ] || { echo "Binary cc-check-darwin-arm64 not found after extraction"; exit 1; }
                fi
                ;;
              *windows-x86_64.zip)
                unzip -q "/tmp/${filename}" -d "$TARGET_DIR" || { echo "Failed to extract ${filename}"; exit 1; }
                if [ "$NAMING" = "npm" ]; then
                  mv "$TARGET_DIR/cc-check-windows-x86_64.exe" "$TARGET_DIR/cc-check-win32-x64.exe" || { echo "Failed to rename cc-check-windows-x86_64.exe"; exit 1; }
                  [ -f "$TARGET_DIR/cc-check-win32-x64.exe" ] || { echo "Binary cc-check-win32-x64.exe not found after extraction"; exit 1; }
                elif [ "$NAMING" = "pypi" ]; then
                  mv "$TARGET_DIR/cc-check-windows-x86_64.exe" "$TARGET_DIR/cc-check-win32-x86_64.exe" || { echo "Failed to rename cc-check-windows-x86_64.exe"; exit 1; }
                  [ -f "$TARGET_DIR/cc-check-win32-x86_64.exe" ] || { echo "Binary cc-check-win32-x86_64.exe not found after extraction"; exit 1; }
                fi
                ;;
            esac
          done
        
        # Make binaries executable
        chmod +x "$TARGET_DIR"/cc-check-* 2>/dev/null || true

